title: SpokenWeb Pedagogy
description: 
  a literary sound studies collection
baseurl: "/spokenwebpedagogy"
url: "https://uvicpraxis.github.io"
header_pages:
  - collection.markdown

# Minima date format

minima:
  date_format: "%b %-d, %Y"

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
